// Generated by CoffeeScript 1.6.3
(function() {
  chrome.browserAction.onClicked.addListener(function(tab) {
    return chrome.windows.create({
      url: "/views/timer.html",
      type: "popup",
      width: 280,
      height: 100
    }, function(window) {
      return console.log("open timer");
    });
  });

}).call(this);
