// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    var openTimer;
    $(document).ready(function() {
      return $("#buttonLogin").click(openTimer);
    });
    return openTimer = function() {
      return chrome.windows.create({
        url: "/views/timer.html",
        type: "popup",
        width: 263,
        height: 50
      }, function(window) {
        return console.log("open timer");
      });
    };
  });

}).call(this);
