// Generated by CoffeeScript 1.6.2
(function() {
  $(function() {
    var API_KEY, HOST, USER_ID, apiKey, contentType, host, initSelect, issues, loadOpenAssignedIssues, postData, setSelectOption, submitTimeEntry;

    API_KEY = "ApiKey";
    HOST = "Host";
    USER_ID = "userId";
    host = "http://ujiroredmine.herokuapp.com";
    issues = "/issues.json?status_id=open&assigned_to_id=";
    contentType = "application/json";
    apiKey = "d8a87e90bb5c59aa786c28be18143cdd993f33c4";
    postData = {
      "time_entry": {
        "issue_id": 0,
        "hours": 0,
        "activity_id": 8,
        "comments": "from Redmine time tracker"
      }
    };
    /*
     On ready document, init.
    */

    $(document).ready(function() {
      $("#submitButton").click(submitTimeEntry);
      return initSelect();
    });
    /*
     Load tickets associated to user ID.
    */

    loadOpenAssignedIssues = function(userId) {
      console.log("load open assigned issues for " + userId);
      return $.ajax({
        type: "GET",
        url: host + issues + userId,
        contentType: contentType,
        headers: {
          "X-Redmine-API-Key": apiKey
        },
        success: setSelectOption
      });
    };
    /*
     Set options to the issue select form.
    */

    setSelectOption = function(res) {
      var arr;

      arr = $.map(res.issues, function(issue) {
        return "<option value=\"" + issue.id + "\">#" + issue.id + " " + issue.subject + "</option>";
      });
      return $("#issueSelect").html(arr.join(""));
    };
    /*
     get data from localStorage
    */

    initSelect = function() {
      var userId;

      apiKey = localStorage[API_KEY];
      host = localStorage[HOST];
      userId = localStorage[USER_ID];
      if ((apiKey == null) || (host == null)) {
        return;
      }
      return loadOpenAssignedIssues(userId);
    };
    /*
     submit to redmine server.
    */

    return submitTimeEntry = function() {
      var issueId;

      issueId = $('#issueSelect').val();
      postData.time_entry.issue_id = issueId;
      postData.time_entry.hours = 1.0;
      return $.ajax({
        type: "POST",
        url: host + ("/issues/" + issueId + "/time_entries.json"),
        contentType: contentType,
        headers: {
          "X-Redmine-API-Key": apiKey
        },
        data: JSON.stringify(postData),
        dataType: "json",
        success: function(msg) {
          return console.log(msg);
        }
      });
    };
  });

}).call(this);
