// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    var API_KEY, CONTENT_TYPE, HOST, ISSUES, USER_ID, init, loadOpenAssignedIssues, postData, setSelectOption, submitTimeEntry;
    API_KEY = "ApiKey";
    HOST = "Host";
    USER_ID = "userId";
    ISSUES = "/issues.json?status_id=open&assigned_to_id=";
    CONTENT_TYPE = "application/json";
    postData = {
      "time_entry": {
        "issue_id": 0,
        "hours": 0,
        "activity_id": 8,
        "comments": "from Redmine time tracker"
      }
    };
    /*
     On ready document, init.
    */

    $(document).ready(function() {
      return init();
    });
    /*
     get data from localStorage, then init.
    */

    init = function() {
      var apiKey, host, userId;
      host = localStorage[HOST];
      apiKey = localStorage[API_KEY];
      userId = localStorage[USER_ID];
      if ((apiKey == null) || (host == null) || (userId == null)) {
        return;
      }
      loadOpenAssignedIssues(host, apiKey, userId);
      return $("#submitButton").click(function() {
        var time;
        time = 1.0;
        return submitTimeEntry(host, apiKey, userId, time);
      });
    };
    /*
     Load tickets associated to user ID.
    */

    loadOpenAssignedIssues = function(host, apiKey, userId) {
      console.log("load open assigned issues for " + userId);
      return $.ajax({
        type: "GET",
        url: host + ISSUES + userId,
        contentType: CONTENT_TYPE,
        headers: {
          "X-Redmine-API-Key": apiKey
        },
        success: setSelectOption
      });
    };
    /*
     Set options to the issue select form.
    */

    setSelectOption = function(res) {
      var arr;
      arr = $.map(res.issues, function(issue) {
        return "<option value=\"" + issue.id + "\">#" + issue.id + " " + issue.subject + "</option>";
      });
      return $("#issueSelect").html(arr.join(""));
    };
    /*
     submit to redmine server.
    */

    return submitTimeEntry = function(host, apiKey, userId, time) {
      var issueId;
      issueId = $('#issueSelect').val();
      postData.time_entry.issue_id = issueId;
      postData.time_entry.hours = time;
      return $.ajax({
        type: "POST",
        url: host + ("/issues/" + issueId + "/time_entries.json"),
        contentType: CONTENT_TYPE,
        headers: {
          "X-Redmine-API-Key": apiKey
        },
        data: JSON.stringify(postData),
        dataType: "json",
        success: function(msg) {
          var _ref;
          return console.log('time_entry id: ' + (msg != null ? (_ref = msg.time_entry) != null ? _ref.id : void 0 : void 0));
        }
      });
    };
  });

}).call(this);
